config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  get 'static_pages/landing_page'

  get 'matching_bars/:characteristic' => 'static_pages#matching_bars'

  root 'static_pages#index'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
     resources :comments #, :sales
   end

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
	validates :name, presence: true
	validates :price, presence: true, numericality: { greater_than: 0 }

	def average_rating
		comments.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :verify_is_admin!, only: [:edit, :update, :destroy, :create]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/search
  def index
    #byebug
    if params[:q]
      search_term = params[:q]
      @products = Product.where("description LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
      respond_with @products
    end

    logger.debug "Product search results:"
    @products.each do |item|
      logger.debug "    Product: #{item.name} - #{item.description}"
    end
    logger.debug "And that's all folks!"
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.paginate(page: params[:page], per_page: 5).order("created_at DESC")
    #byebug
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        flash[:alert] = @product.errors
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        flash[:alert] = @product.errors
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      product_id = params[:id]
      @product = (product_id.nil? ? nil : Product.find_by_id(product_id))
      if @product.nil?
        respond_to do |format|
          format.html { redirect_to products_url, alert: 'Product not found.' }
          format.json { render json: {}, status: :unprocessable_entity }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end

    def verify_is_admin!
      (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(products_url) unless current_user.admin?)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count			= Product.count
		max_updated_at	= Product.maximum(:updated_at).try(:to_s, :number)
		"products/all-#{count}-#{max_updated_at}"
	end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
	<div class="row">
		<hr>
		<p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
			<% if signed_in? && current_user.admin? %>
			<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</p>
		<div class="rated" data-score="<%= comment.rating %>"></div>
		<p><%= "Rating: #{comment.rating}/5" %></p>
		<p><%= comment.body %></p>
	</div>
	<% end %>
	<div class="paginate"><%= will_paginate @comments %></div>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %> (£)<br>
    <%= f.number_field :price, min: 0, class: "text_field", step: 0.01 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache (cache_key_for_products) do %>
	<%= render @products %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid" id="products">
  <div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-2 col-md-4" id="sale-items">
    <% cache product do %>
    <%= link_to(image_tag(product.image_url, class: "img-responsive"), product) %>
      <h1><%= product.name %></h1>
      <p><%= product.description %></p>
      <strong><%= number_to_currency(product.price, unit: "£") %></strong>
      <p id="edit-controls">
      <td><%= link_to 'Show', product %></td>
      <% if signed_in? && current_user.admin? %>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </p>
      <% end %>
    </div><!-- /col -->
    <% end %>
  </div>
</div>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% logger.debug "Product: #{@product.name}"%>

<div class="container-fluid" id="product-show">
	<div class="row">

		<p id="notice"><%= notice %></p>

		<div class="col-sm-2 col-md-2">
			<%= image_tag(@product.image_url, class: "img-responsive") %>
		</div>

		<div class="col-sm-4 col-md-4" id="product-description">	
			<% cache @product do %>
			<p>
				<strong><%= @product.name %></strong>
			</p>
			<p>
				Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>			
			</p>
			<p>
				<%= @product.description %>
			</p>
			<% end %>

			<p>
				<strong><%= number_to_currency(@product.price, unit: "£") %></strong>	
			</p>

			<p class="stripe-checkout">
				<%= form_tag "/payments/create" do %>
					<%= hidden_field_tag(:product_id, @product.id) %>
					<%= render partial: "shared/stripe_checkout_button" %>
				<% end %>
			</p>

			<p>
				<% if signed_in? && current_user.admin? %>
				<%= link_to 'Edit', edit_product_path(@product) %> |
				<% end %>
				<%= link_to 'Back', products_path %>
			</p>
		</div>
	</div>

	<div class="row" id="new-customer-rating">
		<div class="col-sm-4 col-md-4">
			<%= render "new_comment" %>
		</div>	
	</div>

	<div class="row" id="customer-rating">
		<%= render "comments" %>
	</div>

</div>